name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: tar -cfz /tmp/latency_bandwidth_monitor.crbl .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/latency_bandwidth_monitor.crbl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}